name: mobile
description: GoyGoy App For Speech Bubbles
version: 1.0.3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  http: ^0.12.0+1
  intl: ^0.15.7
  shared_preferences: ^0.5.1+1
  firebase_core: ^0.3.1+1
  firebase_performance: ^0.1.0+4
  firebase_analytics: ^2.0.3
  flutter_crashlytics: ^0.2.1+1
  firebase_ml_vision: ^0.6.0+2
  firebase_messaging: ^4.0.0+1
  firebase_admob: ^0.5.3
  image_picker: 0.6.1
  image_cropper: 1.0.2
  crypto: ^2.0.6
  unique_identifier: ^0.0.3
  date_format: ^1.0.5
  flutter_platform_widgets: ^0.9.5
  path_provider: ^0.5.0+1
  package_info: ^0.4.0+2
  flutter_appavailability: 0.0.21
  webview_flutter: 0.3.9+1
  bubble: ^1.1.9+1
  share_extend: ^1.1.0
  permission:
    git: https://github.com/sibelsubasi/permission
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/img/
fonts:
- family: Rubik
  fonts:
    - asset: assets/fonts/Rubik-Regular.ttf
    - asset: assets/fonts/Rubik-Bold.ttf
      weight: 700
    - asset: assets/fonts/Rubik-BoldItalic.ttf
      weight: 700
      style: italic
    - asset: assets/fonts/Rubik-Italic.ttf
      style: italic
- family: Rubik-Light
  fonts:
    - asset: assets/fonts/Rubik-Light.ttf
    - asset: assets/fonts/Rubik-LightItalic.ttf
      style: italic
